### ISSUE TITLE
TypeError Failing Test - Hard

### ISSUE THREAD

**Issue by dfrownfelter** [firstpr/bluebird#2]
This is a slightly difficult one. It would be a good idea to learn about promises first, either from the bluebird docs or from [MDN - Promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise).

Then run the tests and try to figure out where the bug is. If you get stuck or have any questions be sure to ask for help.

**Comment by paulwithap** [comment]
Mine

**Comment by RaghuChandrasekaran** [comment]
I'd like to work on this one.
My initial analysis is that the test runner itself is not executing.

**Comment by dfrownfelter** [comment]
You're right that the test aren't running, but you want to find out why the test aren't running
