### ISSUE TITLE
jshint Error

### ISSUE THREAD

**Issue by dfrownfelter** [firstpr/bluebird#5]
There's a jshint error in the code when running the test suite. Find out what's causing the error and solve it. To work on this bug, comment on this issue, and follow the guide in the readme.

**Comment by Somu2017** [comment]
Hello, I'd like to try to solve this issue. Am I allowed?

**Comment by jinmehta13** [comment]
Hey I'm new to open source. Can I work on this issue? I think I tracked down the error.
